modLoader = "javafml"
loaderVersion = "[39,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "geologicexpansion"
version = "${version}"
displayName = "Geologic Expansion"
authors = "ItsBlackGear"
credits = "ItsBlackGear, Dringles"
description = '''
Geologic Expansion is a mod that adds new features to expand on the overworld and the geological aspects of the game.
'''
logoFile = "icon.png"

[[dependencies.geologicexpansion]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.geologicexpansion]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"