package com.blackgear.geologicexpansion.client.renderer.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class DuckEntityAnimations {

    public static final AnimationDefinition DUCK_WATER_IDLE = AnimationDefinition.Builder.withLength(2f).looping()
        .addAnimation("left_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -2f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.52f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.52f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, -2f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.44f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.44f, KeyframeAnimations.degreeVec(50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(60f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("duck",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, -1.75f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, -2f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("torso",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition DUCK_FISH = AnimationDefinition.Builder.withLength(1.76f).looping()
        .addAnimation("right_wing",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, -50f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.92f, KeyframeAnimations.degreeVec(0f, -30f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, -70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.08f, KeyframeAnimations.degreeVec(0f, -30f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, -50f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, -30f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_wing",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0.68f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.84f, KeyframeAnimations.degreeVec(0f, 50f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.92f, KeyframeAnimations.degreeVec(0f, 30f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.08f, KeyframeAnimations.degreeVec(0f, 30f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, 50f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, 30f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.4f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.4f, KeyframeAnimations.degreeVec(75f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.52f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(75f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.76f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.88f, KeyframeAnimations.degreeVec(90f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.88f, KeyframeAnimations.degreeVec(75f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("torso",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.88f, KeyframeAnimations.degreeVec(17.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition DUCK_FALL = AnimationDefinition.Builder.withLength(0.48f).looping()
        .addAnimation("left_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(-30f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-50f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(25f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(15f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("torso",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(-5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_wing",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, -70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, -70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_wing",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.12f, KeyframeAnimations.degreeVec(0f, 70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.36f, KeyframeAnimations.degreeVec(0f, 70f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();

    public static final AnimationDefinition BABY_TRANSFORM = AnimationDefinition.Builder.withLength(0.0f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
                new Keyframe(0.0f, KeyframeAnimations.scaleVec(2.0f, 2.0f, 2.0f), AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0.0f, KeyframeAnimations.posVec(0.0f, 1.0f, 1.0f), AnimationChannel.Interpolations.LINEAR)))
        .build();
}