package com.blackgear.geologicexpansion.client.renderer.entity.animation;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;

public class GrizzlyAnimations {
    public static final AnimationDefinition GRIZZLY_ATTACK = AnimationDefinition.Builder.withLength(2.04f)
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 5.65f, 3.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 5.65f, 3.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.28f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.52f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-32.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(-52.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.28f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(55f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.28f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.52f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 10.65f, 5.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 15.65f, 4.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.72f, KeyframeAnimations.degreeVec(-82.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0.24f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.posVec(0f, 10.65f, 5.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.72f, KeyframeAnimations.posVec(0f, 15.65f, 4.5f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(-40f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.72f, KeyframeAnimations.degreeVec(-82.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition GRIZZLY_WALKING = AnimationDefinition.Builder.withLength(1.24f).looping()
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(-5.5f, 0.33f, 7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(-5.5f, 0.33f, -7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("chest",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.24f, KeyframeAnimations.degreeVec(0f, 0f, -4f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.48f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.72f, KeyframeAnimations.degreeVec(0f, 0f, 4f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(7.5f, 5f, -7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(7.5f, 5f, 7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0.5f, 0.1f, 2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.posVec(-0.5f, 1f, 0.12f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.posVec(0f, 0.1f, -2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.posVec(0.5f, -0.25f, -0.13f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.posVec(0.5f, 0.1f, 2f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.12f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.44f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(7.5f, 2.33f, 7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, -2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.posVec(-0.5f, -0.25f, -0.13f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.posVec(-0.5f, 0.1f, 2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.posVec(0.5f, 1f, -0.11f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.posVec(0f, 0.1f, -2f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(7.5f, -2.67f, -7.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(22.5f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.12f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, -5f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 1.14f, 0.11f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0.1f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 0.1f, 2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.12f, KeyframeAnimations.posVec(0f, 2f, 0.95f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.posVec(0f, 1.14f, 0.11f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-33.75f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.04f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.96f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(-33.75f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0.1f, 1.2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0.1f, 2f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.44f, KeyframeAnimations.posVec(0f, 2f, 1.06f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.posVec(0f, 0.1f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.posVec(0f, 0.1f, 1.2f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.28f, KeyframeAnimations.degreeVec(45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.64f, KeyframeAnimations.degreeVec(-45f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.8f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition GRIZZLY_WALK = AnimationDefinition.Builder.withLength(2f).looping()
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.36f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.36f, KeyframeAnimations.posVec(0f, -1f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("body",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(1f, 0f, -2.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.52f, KeyframeAnimations.degreeVec(-1f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(1f, 0f, 2.5f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.52f, KeyframeAnimations.degreeVec(-1f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.degreeVec(1f, 0f, -2.5f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.16f, KeyframeAnimations.degreeVec(9f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(0.88f, KeyframeAnimations.degreeVec(-1f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.24f, KeyframeAnimations.degreeVec(7f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(1.36f, KeyframeAnimations.degreeVec(5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM),
                new Keyframe(2f, KeyframeAnimations.degreeVec(7.5f, 0f, 0f),
                    AnimationChannel.Interpolations.CATMULLROM)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.76f, KeyframeAnimations.posVec(0f, 4f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.posVec(0f, 0f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 4f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_front_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.posVec(0f, 0f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.76f, KeyframeAnimations.posVec(0f, 4f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("right_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.76f, KeyframeAnimations.posVec(0f, 4f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.posVec(0f, 0f, -1f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 3f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("left_hind_leg",
            new AnimationChannel(AnimationChannel.Targets.ROTATION,
                new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(0.6f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(1.16f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR),
                new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition BABY_TRANSFORM = AnimationDefinition.Builder.withLength(0f)
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.POSITION,
                new Keyframe(0f, KeyframeAnimations.posVec(0f, -1f, 1f),
                    AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("head",
            new AnimationChannel(AnimationChannel.Targets.SCALE,
                new Keyframe(0f, KeyframeAnimations.scaleVec(1.2f, 1.2f, 1.2f),
                    AnimationChannel.Interpolations.LINEAR))).build();
}